export const Deleteblog = "http://localhost:7000/delete-blog/"
export const authorblog = "http://localhost:7000/getauthorblog/"
export const editblog = "http://localhost:7000/editblog/"
export const sortblog = "http://localhost:7000/sortblog/"
export const singleblog = "http://localhost:7000/getoneblog/"
export const postcomment = "http://localhost:7000/postcomment"
export const theblogcomments = "http://localhost:7000/blogcomment/"
export const authblogs = "htts://localhost:7000/getauthorblog/"